### ISSUE TITLE
get wrong serial port data

### ISSUE THREAD

**Issue by autogyro** [vvkuryshev/GY-MCU90640-RPI-Python#1]
while I run the main program，the IR image looks like  mosaic, after print the raw_data and T_array, fond that there are a lot of data is not the real data, some of them is negative value and some of them is very hight. some times it works well, some times it went wrong.
I used the same one MCU90640 and the same usb cable, used the PC sofware client software built using dotnet, the IR images is good. and that on the MCU unit screen also is good.
I run the python program in win10, 64bit, python 3.6.
Any help would be very appreciated.

**Comment by lashan436** [comment]
is there any way that i can get the pc software that you used.

**Comment by autogyro** [comment]
hi Lashan436, what kinds of OS   in your PC?

**Comment by lashan436** [comment]
windows

**Comment by lashan436** [comment]
win10, 64bit, python 3.6

**Comment by lashan436** [comment]
hi autogyro, i'm also trying to setup this module with raspberry pi 3B which has Rasbian installed in it, does your software support it

**Comment by autogyro** [comment]
I will share to you my fork later，it supports win10 64, python 3.6. 
I didn’t run it on RPI.

**Comment by lashan436** [comment]
hi autogyro,
thank you very much

**Comment by autogyro** [comment]
Hi Iashan436, please check : https://github.com/autogyro/GY-MCU90640-on-PC, actruely, I use MLX90640 , but I think it is the same sensor, you can try . My coding is based on this script and made some changes, it can be run in PC, both Win10 and Ubuntu 16,  I wrote it in a sub threading model, and it can avoid the issues I said.
Good Luck.
